version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-node-browsers
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Install F#
          command: | 
          
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo add-apt-repository ppa:wine/wine-builds
            sudo apt-get install --install-recommends winehq-staging
            sudo apt-get update
            sudo apt-get install fsharp
            
            

      - run:
          name: F# excute
          command: |
            cd source
            fsharpc main.fs
            chmod +x main.exe
            ls -l
      