version: 2
jobs:
  build:
    docker:
      - image: laswonho/wine-with-fsharp
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: F# excute
          command: |
            cd source
            fsharpc main.fs
            chmod +x main.exe
            ls -l
            wine main.exe
      
