version: 2
jobs:
  build:
    docker:
      - image: laswonho/wine-with-fsharp
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: fsharp excute
          command: |
            ls -l
            cd source
            fsharpc main.fs
            ls -l
